# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light source settings
[light_sources]
# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
water_sensitive_check = true
# Enable block entities light source.
block_entities = true
# Enable entities light source.
entities = true
# TNT lighting mode. May be off, simple or fancy.
tnt = "fancy"
# Creeper lighting mode. May be off, simple or fancy.
creeper = "fancy"

[light_sources.settings.entities.minecraft]
axolotl = true
area_effect_cloud = true
arrow = true
armor_stand = true
glow_item_frame = true
